services:
  backend:
    build:
      context: ./backend
    container_name: dental-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: dental-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
